//! Cross-language parity test: `parity_corpus.json` was generated by running
//! Strider's actual pure-Python `nn_dna`/`salt` modules (native extension
//! forcibly blocked via the same `sys.meta_path` technique Strider's own
//! `scripts/bench_native.py` uses) over 200 random sequences, then this
//! crate's outputs are checked against that same corpus to 1e-6 tolerance.
//!
//! This is the Phase 1 "done when" bar from the rewrite plan: outputs must
//! match captured Strider Python outputs, not just be internally
//! consistent.

use serde::Deserialize;
use thermo_core::{duplex_dg, duplex_dh_ds, duplex_tm, is_self_complementary, melting_temperature, reverse_complement, salt};

const TOL: f64 = 1e-6;

#[derive(Deserialize)]
struct Case {
    seq: String,
    dh: f64,
    ds: f64,
    tm_default: f64,
    tm_salty: f64,
    duplex_tm_default: f64,
    dg_default: f64,
    owczarzy: f64,
    owczarzy_mg: f64,
    dg_per_bp: f64,
    reverse_complement: String,
    is_self_complementary: bool,
}

#[derive(Deserialize)]
struct TanChenCase {
    n_pairs: f64,
    na: f64,
    mg: f64,
    value: f64,
}

#[derive(Deserialize)]
struct Corpus {
    results: Vec<Case>,
    tan_chen_cases: Vec<TanChenCase>,
}

fn load_corpus() -> Corpus {
    let raw = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/parity_corpus.json"))
        .expect("parity_corpus.json must exist (generated from strider's pure-Python thermo modules)");
    serde_json::from_str(&raw).expect("parity_corpus.json must be valid JSON matching the Case shape")
}

fn assert_close(name: &str, seq: &str, got: f64, want: f64) {
    assert!(
        (got - want).abs() < TOL,
        "{name} mismatch for {seq:?}: got {got}, want {want} (diff {})",
        (got - want).abs()
    );
}

#[test]
fn thermo_core_matches_strider_python_reference() {
    let corpus = load_corpus();
    assert_eq!(corpus.results.len(), 200, "corpus should have 200 cases");

    for case in &corpus.results {
        let (dh, ds) = duplex_dh_ds(&case.seq).unwrap();
        assert_close("duplex_dh_ds.dh", &case.seq, dh, case.dh);
        assert_close("duplex_dh_ds.ds", &case.seq, ds, case.ds);

        let tm_default = melting_temperature(&case.seq, 250e-9, 0.137, 0.0).unwrap();
        assert_close("melting_temperature(default)", &case.seq, tm_default, case.tm_default);

        let tm_salty = melting_temperature(&case.seq, 400e-9, 0.1958, 0.0).unwrap();
        assert_close("melting_temperature(salty)", &case.seq, tm_salty, case.tm_salty);

        let duplex_tm_default = duplex_tm(&case.seq, 0.05, 0.003, 0.0008, 0.25e-6).unwrap();
        assert_close("duplex_tm(default)", &case.seq, duplex_tm_default, case.duplex_tm_default);

        let dg_default = duplex_dg(&case.seq, 37.0, 1.0, 0.0).unwrap();
        assert_close("duplex_dg(default)", &case.seq, dg_default, case.dg_default);

        let owczarzy = salt::owczarzy_tm_correction(&case.seq, 0.1958, 0.0);
        assert_close("owczarzy_tm_correction", &case.seq, owczarzy, case.owczarzy);

        let owczarzy_mg = salt::owczarzy_tm_correction(&case.seq, 0.05, 0.003);
        assert_close("owczarzy_tm_correction(mg)", &case.seq, owczarzy_mg, case.owczarzy_mg);

        let dg_per_bp = salt::dg_per_bp_salt(0.05, 0.0022, 37.0, "dna");
        assert_close("dg_per_bp_salt", &case.seq, dg_per_bp, case.dg_per_bp);

        assert_eq!(reverse_complement(&case.seq), case.reverse_complement, "reverse_complement for {:?}", case.seq);
        assert_eq!(is_self_complementary(&case.seq), case.is_self_complementary, "is_self_complementary for {:?}", case.seq);
    }
}

#[test]
fn tan_chen_helix_dg_matches_strider_python_reference() {
    let corpus = load_corpus();
    for case in &corpus.tan_chen_cases {
        let got = salt::tan_chen_helix_dg(case.n_pairs, case.na, case.mg, "dna").unwrap();
        assert!(
            (got - case.value).abs() < TOL,
            "tan_chen_helix_dg mismatch for n_pairs={} na={} mg={}: got {got}, want {}",
            case.n_pairs, case.na, case.mg, case.value
        );
    }
}
