//! Cross-language parity test against the real, installed `primer3-py`
//! library (`tests/parity_corpus.json`, generated by
//! `scripts/../gen_primer3_parity_corpus.py` — a copy is not committed
//! since it's a one-off generation script; the corpus JSON is the
//! committed artifact).
//!
//! `primer3-ffi` binds primer3-py's own vendored ("flex") C sources
//! directly rather than reimplementing anything, so this test validates
//! the Rust FFI calling convention (argument order, unit conventions like
//! `thal_args.temp` being Kelvin, struct layout via bindgen) — not
//! primer3's own math, which is already primer3-py's job to get right.

use serde::Deserialize;

const TOL: f64 = 1e-6;

#[derive(Deserialize)]
struct TmCase {
    seq: String,
    mv_conc: f64,
    dv_conc: f64,
    dntp_conc: f64,
    dna_conc: f64,
    tm: f64,
}

#[derive(Deserialize)]
struct ThermoCase {
    seq: String,
    mv_conc: f64,
    dv_conc: f64,
    dntp_conc: f64,
    dna_conc: f64,
    structure_found: bool,
    tm: f64,
    dg: f64,
}

#[derive(Deserialize)]
struct HeterodimerCase {
    seq1: String,
    seq2: String,
    mv_conc: f64,
    dv_conc: f64,
    dntp_conc: f64,
    dna_conc: f64,
    structure_found: bool,
    tm: f64,
    dg: f64,
}

#[derive(Deserialize)]
struct Corpus {
    tm: Vec<TmCase>,
    hairpin: Vec<ThermoCase>,
    homodimer: Vec<ThermoCase>,
    heterodimer: Vec<HeterodimerCase>,
}

fn load_corpus() -> Corpus {
    let raw = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/parity_corpus.json")).expect("parity_corpus.json must exist");
    serde_json::from_str(&raw).expect("parity_corpus.json must be valid JSON")
}

#[test]
fn calc_tm_matches_primer3_py() {
    let corpus = load_corpus();
    assert_eq!(corpus.tm.len(), 450);
    for c in &corpus.tm {
        let got = primer3_ffi::calc_tm(&c.seq, c.mv_conc, c.dv_conc, c.dntp_conc, c.dna_conc).unwrap();
        assert!((got - c.tm).abs() < TOL, "calc_tm mismatch for {:?} @ {:?}: got {got}, want {}", c.seq, (c.mv_conc, c.dv_conc, c.dntp_conc, c.dna_conc), c.tm);
    }
}

#[test]
fn calc_hairpin_matches_primer3_py() {
    let corpus = load_corpus();
    assert_eq!(corpus.hairpin.len(), 450);
    for c in &corpus.hairpin {
        let got = primer3_ffi::calc_hairpin(&c.seq, c.mv_conc, c.dv_conc, c.dntp_conc, c.dna_conc).unwrap();
        assert_eq!(got.structure_found, c.structure_found, "structure_found mismatch for {:?}", c.seq);
        assert!((got.tm.unwrap() - c.tm).abs() < TOL, "hairpin tm mismatch for {:?}", c.seq);
        assert!((got.dg.unwrap() - c.dg).abs() < TOL, "hairpin dg mismatch for {:?}: got {:?}, want {}", c.seq, got.dg, c.dg);
    }
}

#[test]
fn calc_homodimer_matches_primer3_py() {
    let corpus = load_corpus();
    assert_eq!(corpus.homodimer.len(), 450);
    for c in &corpus.homodimer {
        let got = primer3_ffi::calc_homodimer(&c.seq, c.mv_conc, c.dv_conc, c.dntp_conc, c.dna_conc).unwrap();
        assert_eq!(got.structure_found, c.structure_found, "structure_found mismatch for {:?}", c.seq);
        assert!((got.tm.unwrap() - c.tm).abs() < TOL, "homodimer tm mismatch for {:?}", c.seq);
        assert!((got.dg.unwrap() - c.dg).abs() < TOL, "homodimer dg mismatch for {:?}", c.seq);
    }
}

#[test]
fn calc_heterodimer_matches_primer3_py() {
    let corpus = load_corpus();
    assert_eq!(corpus.heterodimer.len(), 60);
    for c in &corpus.heterodimer {
        let got = primer3_ffi::calc_heterodimer(&c.seq1, &c.seq2, c.mv_conc, c.dv_conc, c.dntp_conc, c.dna_conc).unwrap();
        assert_eq!(got.structure_found, c.structure_found, "structure_found mismatch for ({:?}, {:?})", c.seq1, c.seq2);
        assert!((got.tm.unwrap() - c.tm).abs() < TOL, "heterodimer tm mismatch for ({:?}, {:?})", c.seq1, c.seq2);
        assert!((got.dg.unwrap() - c.dg).abs() < TOL, "heterodimer dg mismatch for ({:?}, {:?})", c.seq1, c.seq2);
    }
}
