//! Documented (not hard-gated) comparison between `NativeBackend` and
//! `Primer3Backend` running through the exact same `engine::picker`
//! pipeline on a realistic template — the concrete demonstration that
//! `scan_candidates`/`score_candidates`/`rank` are genuinely
//! backend-agnostic, plus a real numeric comparison of the one metric
//! both backends compute meaningfully (Tm; see `backend_native.rs`'s
//! docs on why hairpin/dimer `tm` is `None` for the native backend).
//!
//! Not a parity gate: the two backends use different Tm models
//! (Primer3's salt-corrected nearest-neighbor thermodynamic alignment vs.
//! Strider's own NN + Owczarzy salt-correction formulas), so exact
//! agreement isn't the goal — "close enough to both be defensible primer
//! Tm estimates" is.

use std::fmt::Write as _;
use std::time::Instant;

use engine::backend::{ThermoBackend, ThermoParams};
use engine::backend_native::NativeBackend;
use engine::backend_primer3::Primer3Backend;
use engine::design_internal::{design_pairs_via_picker, PickerDesignParams};
use engine::picker::{rank, scan_candidates, score_candidates, CandidateConstraints, GcRange, PenaltyWeights, SizeRange, TmRange};

const TEMPLATE: &str = "\
ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCTGTCATCTTCTGTCCCTTCCCAGAAAACCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAGTCTGTGACTTGCACGTACTCCCCTGCCCTCAACAAGATGTTTTGCCAACTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTCCACACCCCCGCCCGGCACCCGCGTCCGCGCCATGGCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGCCCCCACCATGAGCGCTGCTCAGATAGCGATGGTCTGGCCCCTCCTCAGCATCTTATCCGAGTGGAAGGAAATTTGCGTGTGGAGTATTTGGATGACAGAAACACTTTTCGACATAGTGTGGTGGTGCCCTATGAGCCGCCTGAGGTTGGCTCTGACTGTACCACCATCCACTACAACTACATGTGTAACAGTTCCTGCATGGGCGGCATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCAGTGGTAATCTACTGGGACGGAACAGCTTTGAGGTGCGTGTTTGTGCCTGTCCTGGGAGAGACCGGCGCACAGAGGAAGAGAATCTCCGCAAGAAAGGGGAGCCTCACCACGAGCTGCCCCCAGGGAGCACTAAGCGAGCACTGCCCAACAACACCAGCTCCTCTCCCCAGCCAAAGAAGAAACCACTGGATGGAGAATATTTCACCCTTCAGATCCGTGGGCGTGAGCGCTTCGAGATGTTCCGAGAGCTGAATGAGGCCTTGGAACTCAAGGATGCCCAGGCTGGGAAGGAGCCAGGGGGGAGCAGGGCTCACTCCAGCCACCTGAAGTCCAAAAAGGGTCAGTCTACCTCCCGCCATAAAAAACTCATGTTCAAGACAGAAGGGCCTGACTCAGACTGA";

fn constraints() -> CandidateConstraints {
    CandidateConstraints {
        size: SizeRange { min: 18, opt: 20, max: 25 },
        tm: TmRange { min: 50.0, opt: 60.0, max: 72.0 },
        gc: GcRange { min: 30.0, max: 70.0 },
    }
}

#[test]
fn native_backend_vs_primer3_backend_report() {
    let c = constraints();
    let candidates = scan_candidates(TEMPLATE, &c);
    assert!(!candidates.is_empty(), "template must be long enough to produce candidates");

    let primer3 = Primer3Backend;
    let native = NativeBackend;
    let params = ThermoParams::default();
    let weights = PenaltyWeights::default();

    let primer3_scored = rank(score_candidates(&primer3, TEMPLATE, &candidates, &c, params, &weights));
    let native_scored = rank(score_candidates(&native, TEMPLATE, &candidates, &c, params, &weights));

    let mut report = String::new();
    writeln!(report, "# NativeBackend vs. Primer3Backend — engine::picker comparison\n").unwrap();
    writeln!(report, "Generated by `crates/engine/tests/native_vs_primer3_report.rs`. Not a parity gate — see module docs.\n").unwrap();
    writeln!(report, "Template length: {} bp. Constraints: size {:?}, Tm {:?}, GC {:?}.\n", TEMPLATE.len(), c.size, c.tm, c.gc).unwrap();
    writeln!(report, "- Candidates scanned: {}", candidates.len()).unwrap();
    writeln!(report, "- Candidates surviving Primer3Backend's Tm/GC filter: {}", primer3_scored.len()).unwrap();
    writeln!(report, "- Candidates surviving NativeBackend's Tm/GC filter: {}", native_scored.len()).unwrap();

    // Direct Tm comparison across every candidate (not just survivors), since
    // that's the metric both backends compute fully.
    let mut tm_diffs = Vec::new();
    for cand in &candidates {
        let seq = cand.sequence(TEMPLATE);
        let p3_tm = primer3.calc_tm(seq, params);
        let native_tm = native.calc_tm(seq, params);
        tm_diffs.push((p3_tm - native_tm).abs());
    }
    let mean_tm_diff = tm_diffs.iter().sum::<f64>() / tm_diffs.len() as f64;
    let max_tm_diff = tm_diffs.iter().cloned().fold(0.0_f64, f64::max);
    writeln!(report, "\n## Tm agreement across all {} scanned candidates\n", candidates.len()).unwrap();
    writeln!(report, "- Mean |Tm difference|: {mean_tm_diff:.2} °C").unwrap();
    writeln!(report, "- Max |Tm difference|: {max_tm_diff:.2} °C").unwrap();

    writeln!(report, "\n## Top 5 ranked candidates per backend\n").unwrap();
    writeln!(report, "### Primer3Backend").unwrap();
    writeln!(report, "| seq | tm | gc% | penalty |").unwrap();
    writeln!(report, "|---|---|---|---|").unwrap();
    for sc in primer3_scored.iter().take(5) {
        writeln!(report, "| {} | {:.1} | {:.1} | {:.2} |", sc.candidate.sequence(TEMPLATE), sc.tm, sc.gc_percent, sc.penalty).unwrap();
    }
    writeln!(report, "\n### NativeBackend").unwrap();
    writeln!(report, "| seq | tm | gc% | penalty |").unwrap();
    writeln!(report, "|---|---|---|---|").unwrap();
    for sc in native_scored.iter().take(5) {
        writeln!(report, "| {} | {:.1} | {:.1} | {:.2} |", sc.candidate.sequence(TEMPLATE), sc.tm, sc.gc_percent, sc.penalty).unwrap();
    }

    let top5_primer3: std::collections::HashSet<_> = primer3_scored.iter().take(5).map(|sc| sc.candidate).collect();
    let top5_native: std::collections::HashSet<_> = native_scored.iter().take(5).map(|sc| sc.candidate).collect();
    let overlap = top5_primer3.intersection(&top5_native).count();
    writeln!(report, "\nTop-5 candidate overlap (same start/end window in both rankings): {overlap}/5").unwrap();
    writeln!(
        report,
        "\nSame `engine::picker` code path (`scan_candidates`/`score_candidates`/`rank`) ran unmodified against both backends — this is the concrete proof that the picker is backend-agnostic, which is the actual point of this phase. Tm differences reflect genuinely different (both standard) thermodynamic models, not a bug."
    )
    .unwrap();

    // `design_internal::design_pairs_via_picker` — the first full pair-
    // design path proven to run on either backend (Phase 5's originally
    // open item). Timed deliberately: this is where a real, measured
    // performance gap between the two backends showed up during
    // development (see `design_internal::MAX_POOL_FOR_PAIRING`'s doc
    // comment for the full investigation) — `Primer3Backend`'s
    // `calc_heterodimer` is a ~120µs DP alignment behind a global FFI
    // mutex, vs. `NativeBackend`'s pure-Rust equivalent, so pairing is
    // expected to be meaningfully slower on Primer3Backend even after
    // capping the combinatorial pool. Recorded here as an ongoing
    // characteristic to watch, not a regression gate (no fixed threshold
    // asserted — CI hardware varies).
    let pair_params = PickerDesignParams { product_size_range: (100, 300), ..PickerDesignParams::default() };
    let target_start = TEMPLATE.len() / 2;
    let target_end = target_start + 20;

    let t0 = Instant::now();
    let primer3_pairs = design_pairs_via_picker(&primer3, TEMPLATE, target_start, target_end, &pair_params, params);
    let primer3_pair_time = t0.elapsed();

    let t0 = Instant::now();
    let native_pairs = design_pairs_via_picker(&native, TEMPLATE, target_start, target_end, &pair_params, params);
    let native_pair_time = t0.elapsed();

    writeln!(report, "\n## `design_pairs_via_picker` (SEQUENCE_TARGET-equivalent pair design)\n").unwrap();
    writeln!(report, "Target: [{target_start}, {target_end}). Product size range: {:?}.\n", pair_params.product_size_range).unwrap();
    writeln!(report, "| backend | pairs found | wall time |").unwrap();
    writeln!(report, "|---|---|---|").unwrap();
    writeln!(report, "| Primer3Backend | {} | {:.1?} |", primer3_pairs.len(), primer3_pair_time).unwrap();
    writeln!(report, "| NativeBackend | {} | {:.1?} |", native_pairs.len(), native_pair_time).unwrap();
    writeln!(
        report,
        "\nBoth backends run the identical `pick_pairs` code path; every returned pair from both respects the target-flanking, non-overlap, and product-size constraints (asserted in `design_internal`'s own tests, not re-checked here)."
    )
    .unwrap();

    let out_path = concat!(env!("CARGO_MANIFEST_DIR"), "/native_vs_primer3_report.md");
    std::fs::write(out_path, &report).expect("failed to write comparison report");
    println!("{report}");

    // Loose, documented sanity bar (not a parity gate).
    assert!(!primer3_scored.is_empty(), "Primer3Backend should find at least one bounds-respecting candidate in a real CDS");
    assert!(!native_scored.is_empty(), "NativeBackend should find at least one bounds-respecting candidate in a real CDS");
    assert!(mean_tm_diff.is_finite());
    assert!(!primer3_pairs.is_empty(), "Primer3Backend should find at least one pair flanking the target");
    assert!(!native_pairs.is_empty(), "NativeBackend should find at least one pair flanking the target");
}
